apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
  namespace: dapr-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411

---
kind: Service
apiVersion: v1
metadata:
  name: zipkin
  labels:
    app: zipkin
  namespace: dapr-app
  annotations:
    fluxcd.io/ignore: "true"
spec:
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  type: ClusterIP

---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zipkin
  namespace: dapr-app
  annotations:
    fluxcd.io/ignore: "true"
spec:
  type: exporters.zipkin
  metadata:
    - name: enabled
      value: "true"
    - name: exporterAddress
      value: "http://zipkin.dapr-app.svc.cluster.local:9411/api/v2/spans"
