apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    app: frontend
  annotations:
    fluxcd.io/ignore: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - makabe.info
      secretName: tls-secret
  rules:
    - host: makabe.info
      http:
        paths:
          - path: /
            backend:
              serviceName: localhost
              servicePort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: localhost
  namespace: podinfo
  annotations:
    fluxcd.io/ignore: "false"
spec:
  externalName: localhost
  type: ExternalName
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    fluxcd.io/ignore: "false"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tomakabe@microsoft.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
