apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: getsecret
  name: getsecret
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getsecret
  template:
    metadata:
      labels:
        app: getsecret
      name: getsecret
    spec:
      containers:
        - name: getsecret
          image: torumakabe/getsecret:from-env
          env:
            - name: SECRET_JOKE
              valueFrom:
                secretKeyRef:
                  name: joke
                  key: joke

---
apiVersion: v1
kind: Service
metadata:
  name: getsecret
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: getsecret
  type: LoadBalancer
