apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: consul
  namespace: consul
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
spec:
  releaseName: consul
  chart:
    repository: https://helm.releases.hashicorp.com/
    name: consul
    version: 0.21.0
  values:
    global:
      name: consul
    connectInject:
      enabled: true
    client:
      enabled: true
      grpc: true
    syncCatalog:
      enabled: true
    server:
      storageClass: managed-premium-bind-wait
