---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.6

spec:
  releaseName: kured
  chart:
    repository: https://weaveworks.github.io/kured/
    name: kured
    version: 2.3.1
  values:
    image:
      repository: weaveworks/kured:1.6.1
      # tag: 1.6.1
    extraArgs:
      time-zone: "Asia/Tokyo"
      start-time: "09:00"
      end-time: "17:00"
