---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
    filter.fluxcd.io/prometheus-node-exporter: semver:~v1.0
spec:
  releaseName: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts/
    name: prometheus-operator
    version: 9.3.2
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: managed-premium-bind-wait
              resources:
                requests:
                  storage: 5Gi
        additionalScrapeConfigs:
          - job_name: node
            static_configs:
              - targets: ["localhost:9100"]
        serviceMonitorSelector: {} # workaround https://github.com/coreos/prometheus-operator/issues/2840
    prometheus-node-exporter:
      image:
        repository: quay.io/prometheus/node-exporter
        tag: v1.0.0
      podLabels:
        jobLabel: node-exporter
      extraArgs:
        - --collector.systemd
        - --collector.processes
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
        - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: managed-premium-bind-wait
              resources:
                requests:
                  storage: 5Gi
    grafana:
      persistence:
        enabled: true
        storageClassName: managed-premium-bind-wait
        accessModes: ["ReadWriteOnce"]
        size: 5Gi
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "sample"
              orgId: 1
              folder: "sample"
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards/sample
      dashboards:
        sample:
          kubernetes-cluster:
            gnetId: 6417
            datasource: Prometheus
          one-node-exporter:
            gnetId: 11074
            datasource: Prometheus
          node-exporter-full:
            gnetId: 1860
            datasource: Prometheus
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
