apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: dapr-pub-sub
  annotations:
    fluxcd.io/ignore: "false"
spec:
  tracing:
    enabled: true
    expandParams: true
    includeBody: true
