apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-bind-wait
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
    # temporarily comment out https://github.com/Azure/AKS/issues/1537
    # storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype : Premium_LRS
  kind: Managed
volumeBindingMode: WaitForFirstConsumer
