apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplyapp
  labels:
    app: multiply
  namespace: dapr
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiply
  template:
    metadata:
      labels:
        app: multiply
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "multiplyapp"
        dapr.io/port: "5000"
        dapr.io/config: "tracing"
    spec:
      containers:
        - name: multiply
          image: dapriosamples/distributed-calculator-slow-python:edge
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
