---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
spec:
  releaseName: dapr
  chart:
    repository: https://daprio.azurecr.io/helm/v1/repo/
    name: dapr
    version: 0.4.2
