---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: dapr-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami/
    name: redis
    version: 10.6.7
  values:
    existingSecret: "redis-secret"
    existingSecretPasswordKey: "redis-password"
