---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.8.0
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: build-674785101-674785108-linux-arm
