apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: dapr
  annotations:
    fluxcd.io/ignore: "true"
spec:
  tracing:
    enabled: true
    expandParams: true
    includeBody: true
