apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: python
  namespace: dapr-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "pythonapp"
    spec:
      containers:
        - name: python
          image: dapriosamples/hello-k8s-python:edge
